### PR TITLE
fix: fixed can list table pagination bug

### LINKED ISSUE #3524: CANs list not showing accurate results due to pagination being stuck
## Expected Behavior
When viewing All CANs list, when changing the FY dropdown, CANs list should show accurate CANs for the selected FY.

## Current Behavior
When viewing the All CANs list, filtering and viewing CANs by FY dropdown works great until I navigate to a page 2 via the pagination if a FY has enough CANs to warrant multiple pages. By navigating to a page 2 and then selecting a different FY, the CANs from that FY do not appear. Seems like table is stuck on a page 2 even if it shouldn't exist?

## Steps to Reproduce
1. Sign in as Budget Team Member.
2. Navigate to All CANs list and see CANs for FY 2025.
3. Select 2023 in FY dropdown.
4. Scroll to bottom of CANs table and click on page 2 of pagination.
5. Select 2025 in FY dropdown.
6. See CANs that appeared before no longer appear.

## Context
1. Not returning accurate display of CANs. 
2. Viewed in dev environment.

https://github.com/user-attachments/assets/07d266ae-7176-41eb-81b0-b44883337da0

### PR DESCRIPTION
**Pull request by weimiao67**
## What changed

Fixes #3524 

## How to test

Refer to #3524 for steps

## Definition of Done Checklist
- [x] OESA: Code refactored for clarity
- [x] OESA: Dependency rules followed
- [x] Automated unit tests updated and passed
- [x] Automated integration tests updated and passed
- [x] Automated quality tests updated and passed
- [x] Automated load tests updated and passed
- [x] Automated a11y tests updated and passed
- [x] Automated security tests updated and passed
- [x] 90%+ Code coverage achieved
- [x] Form validations updated

### CODE REVIEW

File: frontend/src/components/CANs/CANBudgetLineTable/CANBudgetLineTable.jsx [hunk 1]
```diff
@@ -64,6 +70,7 @@ const CANBudgetLineTable = ({ budgetLines, totalFunding, tableType = "can" }) =>
                     itemsPerPage={ITEMS_PER_PAGE}
                 />
             )}
+            <DebugCode data={currentPage} />
```
Comment (fpigeonjr) [inline frontend/src/components/CANs/CANBudgetLineTable/CANBudgetLineTable.jsx:73]: we will want to remove this DebugCode

File: frontend/cypress/e2e/canList.cy.js [hunk 2]
```diff
@@ -76,6 +76,16 @@ describe("CAN List", () => {
             .find("svg")
             .should("have.attr", "aria-hidden", "true");
 
+        // switch fiscal year to 2025
```
Comment (fpigeonjr) [inline frontend/cypress/e2e/canList.cy.js:79]: 🧪 thx for adding a test to simulate the bug

**Review by fpigeonjr — APPROVED** [review]
🏆 Great job @weimiao67

File: frontend/src/components/CANs/CANBudgetLineTable/CANBudgetLineTable.jsx (hunk 1 above)
Comment (weimiao67) [reply frontend/src/components/CANs/CANBudgetLineTable/CANBudgetLineTable.jsx]: removed

**Review by rajohnson90 — APPROVED** [review]

**Review by maiyerlee — APPROVED** [review]
