### PR TITLE
fix: do not show services component form if agreement is NYD

### LINKED ISSUE #4398: bug: service component optional checkbox is not always present
> Summary from PL today 
> - SC optional checkbox missing
> - (other items listed)
 _Originally posted by @kimschulke in [#4355](https://github.com/HHS/OPRE-OPS/issues/4355#issuecomment-3285821412)_

### PR DESCRIPTION
**Pull request by fpigeonjr**
## What changed

This PR prevents the ServicesComponentForm from being displayed when an agreement is in "Not Yet Developed" (NYD) status by adding conditional rendering and early return logic.

- Adds conditional wrapper around ServicesComponents to hide it when agreement is NYD
- Implements early return in ServicesComponentForm with error message when serviceTypeReq is missing
- Extracts isNotDevelopedYet helper function to determine agreement status

## Issue

- closes #4398
- blocked by #4410

## How to test

1. login as power user
2. goto a not yet developed agreement type
3. click edit 
4. should not see the services components form

## Screenshots
- note no Services Component form on agreement 2
image

## Definition of Done Checklist
- [x] OESA: Code refactored for clarity
- [x] OESA: Dependency rules followed
- [x] Automated unit tests updated and passed
- [x] Automated integration tests updated and passed
- [x] Automated quality tests updated and passed
- [x] Automated load tests updated and passed
- [x] Automated a11y tests updated and passed
- [x] Automated security tests updated and passed
- [x] 90%+ Code coverage achieved
- [-] Form validations updated

### CODE REVIEW

File: frontend/src/components/BudgetLineItems/CreateBLIsAndSCs/CreateBLIsAndSCs.jsx [hunk 1]
```diff
@@ -162,11 +163,13 @@ export const CreateBLIsAndSCs = ({
             {workflow === "none" && (
                 // NOTE: this is the Agreement Details page
                 <>
-                    <ServicesComponents
-                        serviceRequirementType={selectedAgreement.service_requirement_type}
-                        agreementId={selectedAgreement.id}
-                        isEditMode={isEditMode}
-                    />
+                    {!isAgreementNotYetDeveloped && (
```
Comment (fpigeonjr) [inline frontend/src/components/BudgetLineItems/CreateBLIsAndSCs/CreateBLIsAndSCs.jsx:166]: this is the crux of the PR
