### PR TITLE
fix: fixes CANList and CANTable mismatch bug

### LINKED ISSUE #3464: Available budget in CANTableRow is inaccurate
Image

## Expected Behavior
Money in the FY 2025 CANs Available Budget data visualization should match total amount in $ Available column in All CANs list.

## Current Behavior
Money in the FY 2025 CANs Available Budget data visualization doesn't match total amount in $ Available column in All CANs list.

## Steps to Reproduce
1. Sign in to OPS
2. Go to All CANs list
3. Compare FY 2025 CANs Available Budget data visualization ($3,000,000) to total amount in $ Available column in All CANs list ($1,000,000)

## Context
1. Viewed in staging environment

### PR DESCRIPTION
**Pull request by fpigeonjr**
## What changed

- fixes #3464

## How to test

same steps as #3464

image

## Definition of Done Checklist
- [x] OESA: Code refactored for clarity
- [x] OESA: Dependency rules followed
- [x] Automated unit tests updated and passed
- [x] Automated integration tests updated and passed
- [x] Automated quality tests updated and passed
- [x] Automated load tests updated and passed
- [x] Automated a11y tests updated and passed
- [x] Automated security tests updated and passed
- [x] 90%+ Code coverage achieved
- <del>[ ] Form validations updated

### CODE REVIEW

**Comment by fpigeonjr** [comment]
will add a e2e tests replicating the bug

**Review by maiyerlee — APPROVED** [review]

File: frontend/src/components/CANs/CANTable/CANTable.jsx [hunk 1]
```diff
@@ -17,8 +17,7 @@ import styles from "./style.module.css";
  * @returns {JSX.Element}
  */
 const CANTable = ({ cans, fiscalYear }) => {
-    // TODO: once in prod, change this to 25
-    const CANS_PER_PAGE = 10;
+    const CANS_PER_PAGE = import.meta.env.MODE === "production" ? 25 : 10;
```
Comment (jonnalley) [inline frontend/src/components/CANs/CANTable/CANTable.jsx:20]: Nice

File: frontend/src/components/CANs/CANTable/CANTableRow.jsx [hunk 2]
```diff
@@ -13,7 +12,7 @@ import { displayActivePeriod } from "./CANTableRow.helpers";
  * @param {Object} props
  * @param {number} props.activePeriod - Active Period in years
  * @param {number} props.canId - CAN ID
- * @param {number|"TBD"} props.fiscalYear - Fiscal Year
+ * @param {number} props.fiscalYear - Selected Fiscal Year
```
Comment (jonnalley) [inline frontend/src/components/CANs/CANTable/CANTableRow.jsx:15]: So will that still be OK for cans without a set budget yet?  Pardon my ignorance

Comment (fpigeonjr) [reply frontend/src/components/CANs/CANTable/CANTableRow.jsx:15]: the crux of the fix is using the selected fiscal year and not a CAN attribute. Think we fixed CANs without funding budgets in another PR.

**Review by weimiao67 — APPROVED** [review]
Works well locally.
